'use client';

import { useMemo, useEffect } from 'react';
import { fmt } from '@/lib/production';
import type { KPIResult } from '@/types';
import type { ActionInsight } from '@/lib/insights';
import type { ScenarioType, ScenarioResult } from '@/lib/scenario';

interface BoardBriefModalProps {
  open: boolean;
  onClose: () => void;
  kpis: KPIResult;
  yearMin: number;
  yearMax: number;
  focusedState: string | null;
  forecastQuality: number;
  projected2028: number | null;
  insights: ActionInsight[];
  scenarioType: ScenarioType;
  scenarioResult: ScenarioResult;
}

function qualityLabel(q: number) {
  if (q >= 0.7) return 'High';
  if (q >= 0.4) return 'Medium';
  return 'Low';
}

/* ─── Plain-text generator (copy / download) ───────────────────── */
function generateBrief(p: Omit<BoardBriefModalProps, 'open' | 'onClose'>): string {
  const { kpis, yearMin, yearMax, focusedState, forecastQuality, projected2028, insights, scenarioType, scenarioResult } = p;
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const yoyDir = (kpis.yoyOilGrowthPct ?? 0) >= 0 ? 'up' : 'down';
  const yoyAbs = kpis.yoyOilGrowthPct !== null ? Math.abs(kpis.yoyOilGrowthPct).toFixed(1) : 'N/A';
  const focusLine = focusedState ? `Focus: ${focusedState}` : 'All Tracked States';

  const headlineYoY =
    kpis.yoyOilGrowthPct !== null ? `, ${yoyDir} ${yoyAbs}% year-over-year` : '';
  const headline =
    `U.S. tracked oil production reached ${fmt(kpis.totalOilLatestKbbl)} Kbbl in ${kpis.latestYear}${headlineYoY}. ` +
    `${kpis.topOilState} leads with ${kpis.topOilSharePct.toFixed(0)}% of total tracked output across ${kpis.activeStates} EIA-covered states. ` +
    (projected2028
      ? `The ${scenarioType} scenario projects ${fmt(projected2028)} Kbbl by 2028 at ${(scenarioResult.cagrUsed * 100).toFixed(2)}%/yr CAGR.`
      : 'Forecast unavailable — expand data coverage.');

  const topInsights = insights.slice(0, 3);
  const findingsText = topInsights
    .map((ins, i) => `${i + 1}. ${ins.title}: ${ins.explanation}`)
    .join('\n');

  const highRisks = insights.filter((ins) => ins.severity === 'High');
  const risk2 = highRisks.length > 0
    ? highRisks[0].explanation
    : 'Monitor forecast quality — model confidence is limited by available data window.';
  const risksText = `1. ${scenarioResult.topRisk}\n2. ${risk2}`;

  const actionsText = insights.slice(0, 2)
    .map((ins, i) => `${i + 1}. ${ins.action}`)
    .join('\n');

  const deltaLine =
    scenarioResult.deltaVsBasePct !== null
      ? ` (${scenarioResult.deltaVsBasePct >= 0 ? '+' : ''}${scenarioResult.deltaVsBasePct.toFixed(1)}% vs. base case)`
      : '';

  const RULE = '━'.repeat(54);

  return [
    `FIELDSIGNAL AI · EXECUTIVE BOARD BRIEF`,
    `EIA U.S. Production Data  |  ${yearMin}–${yearMax}  |  ${date}`,
    `${focusLine}`,
    '', RULE, '',
    `HEADLINE`, '', headline,
    '', RULE, '',
    `KEY FINDINGS`, '', findingsText || '1. Expand EIA data coverage to generate findings.',
    '', RULE, '',
    `STRATEGIC RISKS`, '', risksText,
    '', RULE, '',
    `RECOMMENDED ACTIONS`, '', actionsText || '1. Expand EIA data coverage to generate recommendations.',
    '', RULE, '',
    `SCENARIO ANALYSIS`, '',
    `Scenario: ${scenarioType}  |  CAGR: ${(scenarioResult.cagrUsed * 100).toFixed(2)}%/yr`,
    `Projected 2028: ${fmt(scenarioResult.projected2028)} Kbbl${deltaLine}`,
    `Confidence: ${scenarioResult.confidence} · Scenario estimate`,
    `Best diversification candidate: ${scenarioResult.bestDiversification}`,
    '', RULE, '',
    `METHODOLOGY & ASSUMPTIONS`, '',
    `Data source: EIA U.S. Energy Information Administration`,
    `Forecast: 5-year CAGR model, clamped [−5%, +20%], extrapolated to 2028/2030`,
    `Model quality: ${forecastQuality.toFixed(2)}/1.00 (${qualityLabel(forecastQuality)} confidence)`,
    `Coverage: ${kpis.activeStates} states through ${kpis.latestYear}`,
    `Scenario estimates: FieldSignal model outputs — not official EIA forecasts`,
    `Action Center: FieldSignal heuristics — not official EIA analysis`,
    '', RULE, '',
    `Generated by FieldSignal AI  ·  Based on EIA data  ·  ${date}`,
    `For strategic planning use only. Not investment advice.`,
  ].join('\n');
}

/* ─── Structured visual renderer ───────────────────────────────── */
function BriefDivider() {
  return <div style={{ borderTop: '1px solid #152333' }} className="my-4" />;
}

function SectionHead({ title }: { title: string }) {
  return (
    <p className="text-[9px] font-bold text-slate-600 uppercase tracking-[0.16em] mb-3">{title}</p>
  );
}

function BriefRenderer(p: Omit<BoardBriefModalProps, 'open' | 'onClose'>) {
  const {
    kpis, yearMin, yearMax, focusedState, forecastQuality,
    projected2028, insights, scenarioType, scenarioResult,
  } = p;

  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });
  const focusLine = focusedState ? `Focus: ${focusedState}` : 'All Tracked States';
  const yoyDir = (kpis.yoyOilGrowthPct ?? 0) >= 0 ? 'up' : 'down';
  const yoyAbs = kpis.yoyOilGrowthPct !== null ? Math.abs(kpis.yoyOilGrowthPct).toFixed(1) : null;

  const headline =
    `U.S. tracked oil production reached ${fmt(kpis.totalOilLatestKbbl)} Kbbl in ${kpis.latestYear}` +
    (yoyAbs ? `, ${yoyDir} ${yoyAbs}% year-over-year.` : '.') +
    ` ${kpis.topOilState} leads with ${kpis.topOilSharePct.toFixed(0)}% of total tracked output across ${kpis.activeStates} EIA-covered states.` +
    (projected2028
      ? ` The ${scenarioType} scenario projects ${fmt(projected2028)} Kbbl by 2028 at ${(scenarioResult.cagrUsed * 100).toFixed(2)}%/yr CAGR.`
      : ' Forecast unavailable — expand data coverage.');

  const topInsights = insights.slice(0, 3);
  const highRisks = insights.filter((ins) => ins.severity === 'High');
  const risk2 = highRisks.length > 0
    ? highRisks[0].explanation
    : 'Monitor forecast quality — model confidence is limited by available data window.';

  const deltaLine =
    scenarioResult.deltaVsBasePct !== null
      ? ` (${scenarioResult.deltaVsBasePct >= 0 ? '+' : ''}${scenarioResult.deltaVsBasePct.toFixed(1)}% vs. base)`
      : '';

  const qLabel = qualityLabel(forecastQuality);
  const confCls =
    scenarioResult.confidence === 'High'
      ? 'text-teal-400 bg-teal-400/10 border-teal-400/25'
      : scenarioResult.confidence === 'Medium'
      ? 'text-slate-400 bg-slate-400/10 border-slate-400/25'
      : 'text-rose-300/80 bg-rose-400/8 border-rose-400/20';

  return (
    <div>
      {/* Brief header */}
      <div className="pb-4" style={{ borderBottom: '1px solid #152333' }}>
        <p className="text-[12px] font-bold text-slate-100 tracking-tight">
          FieldSignal AI · Executive Board Brief
        </p>
        <div className="flex items-center gap-2 mt-2 flex-wrap">
          <span className="text-[10px] text-slate-500">EIA U.S. Production Data</span>
          <span className="text-[9px] text-slate-700">·</span>
          <span className="text-[10px] text-slate-500 tabular-nums">{yearMin}–{yearMax}</span>
          <span className="text-[9px] text-slate-700">·</span>
          <span className="text-[10px] text-slate-500">{date}</span>
          <span className="text-[9px] text-slate-700">·</span>
          <span className="text-[10px] text-teal-500/70">{focusLine}</span>
        </div>
      </div>

      <BriefDivider />

      {/* Headline */}
      <div className="mb-1">
        <SectionHead title="Headline" />
        <p className="text-[12px] text-slate-300 leading-relaxed">{headline}</p>
      </div>

      <BriefDivider />

      {/* Key Findings */}
      <div className="mb-1">
        <SectionHead title="Key Findings" />
        {topInsights.length > 0 ? (
          <ol className="flex flex-col gap-3">
            {topInsights.map((ins, i) => (
              <li key={ins.id} className="flex gap-3">
                <span className="text-[10px] text-slate-600 tabular-nums shrink-0 mt-0.5 w-4">{i + 1}.</span>
                <div>
                  <p className="text-[11px] font-semibold text-slate-200 leading-snug">{ins.title}</p>
                  <p className="text-[11px] text-slate-500 leading-relaxed mt-0.5">{ins.explanation}</p>
                </div>
              </li>
            ))}
          </ol>
        ) : (
          <p className="text-[11px] text-slate-500">Expand EIA data coverage to generate findings.</p>
        )}
      </div>

      <BriefDivider />

      {/* Strategic Risks */}
      <div className="mb-1">
        <SectionHead title="Strategic Risks" />
        <ol className="flex flex-col gap-3">
          <li className="flex gap-3">
            <span className="text-[10px] text-slate-600 tabular-nums shrink-0 mt-0.5 w-4">1.</span>
            <p className="text-[11px] text-slate-400 leading-relaxed">{scenarioResult.topRisk}</p>
          </li>
          <li className="flex gap-3">
            <span className="text-[10px] text-slate-600 tabular-nums shrink-0 mt-0.5 w-4">2.</span>
            <p className="text-[11px] text-slate-400 leading-relaxed">{risk2}</p>
          </li>
        </ol>
      </div>

      <BriefDivider />

      {/* Recommended Actions */}
      <div className="mb-1">
        <SectionHead title="Recommended Actions" />
        {insights.slice(0, 2).length > 0 ? (
          <ol className="flex flex-col gap-3">
            {insights.slice(0, 2).map((ins, i) => (
              <li key={ins.id} className="flex gap-3">
                <span className="text-[10px] text-slate-600 tabular-nums shrink-0 mt-0.5 w-4">{i + 1}.</span>
                <p className="text-[11px] text-slate-400 leading-relaxed">{ins.action}</p>
              </li>
            ))}
          </ol>
        ) : (
          <p className="text-[11px] text-slate-500">Expand EIA data coverage to generate recommendations.</p>
        )}
      </div>

      <BriefDivider />

      {/* Scenario Analysis */}
      <div className="mb-1">
        <SectionHead title="Scenario Analysis" />
        <div
          className="rounded-lg px-4 py-3.5 flex flex-col gap-2.5"
          style={{ background: 'rgba(4,10,18,0.55)', border: '1px solid rgba(18,32,50,0.9)' }}
        >
          <div className="flex items-center gap-2 flex-wrap">
            <span className="text-[11px] font-semibold text-slate-300">{scenarioType} scenario</span>
            <span className="text-[9px] text-slate-700">·</span>
            <span className="text-[10px] text-slate-500 tabular-nums">{(scenarioResult.cagrUsed * 100).toFixed(2)}%/yr CAGR</span>
            <span className={`text-[9px] font-semibold rounded-full px-1.5 py-0.5 border ${confCls}`}>
              {scenarioResult.confidence} confidence
            </span>
          </div>
          <div className="flex items-baseline gap-2">
            <span className="text-2xl font-bold text-white tabular-nums tracking-tight">
              {fmt(scenarioResult.projected2028)}
            </span>
            <span className="text-[11px] text-slate-500">Kbbl projected 2028{deltaLine}</span>
          </div>
          <p className="text-[10px] text-slate-500">
            Diversification candidate:{' '}
            <span className="text-teal-400/80 font-semibold">{scenarioResult.bestDiversification}</span>
          </p>
        </div>
      </div>

      <BriefDivider />

      {/* Methodology */}
      <div className="mb-1">
        <SectionHead title="Methodology & Assumptions" />
        <div className="flex flex-col gap-1.5">
          <p className="text-[11px] text-slate-500 leading-relaxed">
            Data source: EIA U.S. Energy Information Administration
          </p>
          <p className="text-[11px] text-slate-500 leading-relaxed">
            Forecast: 5-year CAGR model, clamped [−5%, +20%], extrapolated to 2028/2030
          </p>
          <p className="text-[11px] text-slate-500 leading-relaxed">
            Model quality:{' '}
            <span className="tabular-nums">{forecastQuality.toFixed(2)}/1.00</span>{' '}
            ({qLabel} confidence) · {kpis.activeStates} states through {kpis.latestYear}
          </p>
          <p className="text-[10px] text-slate-600 leading-relaxed mt-1.5">
            Scenario estimates are FieldSignal model outputs — not official EIA forecasts.
            Action Center signals are FieldSignal heuristics — not official EIA analysis.
          </p>
        </div>
      </div>

      <BriefDivider />

      <p className="text-[10px] text-slate-600 leading-relaxed">
        Generated by FieldSignal AI · Based on EIA data · {date}
      </p>
      <p className="text-[9px] text-slate-700 mt-0.5">
        For strategic planning use only. Not investment advice.
      </p>
    </div>
  );
}

/* ─── Modal shell ───────────────────────────────────────────────── */
export function BoardBriefModal(props: BoardBriefModalProps) {
  const { open, onClose } = props;

  useEffect(() => {
    function handleKey(e: KeyboardEvent) {
      if (e.key === 'Escape') onClose();
    }
    if (open) window.addEventListener('keydown', handleKey);
    return () => window.removeEventListener('keydown', handleKey);
  }, [open, onClose]);

  const brief = useMemo(() => {
    if (!open) return '';
    const { open: _o, onClose: _c, ...rest } = props;
    return generateBrief(rest);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  if (!open) return null;

  function copyToClipboard() {
    navigator.clipboard.writeText(brief).catch(() => {/* silently ignore */});
  }

  function download() {
    const blob = new Blob([brief], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `fieldsignal_board_brief_${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  const { open: _o, onClose: _c, ...rendererProps } = props;

  return (
    <div className="fixed inset-0 z-50 flex items-stretch justify-end">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
        onClick={onClose}
      />

      {/* Side sheet */}
      <div
        className="relative z-10 flex flex-col w-full max-w-xl"
        style={{
          background: '#07111e',
          borderLeft: '1px solid #1d3a52',
          boxShadow: '-8px 0 48px rgba(0,0,0,0.7)',
        }}
      >
        {/* Header */}
        <div
          className="flex items-center justify-between px-6 py-4 shrink-0"
          style={{ borderBottom: '1px solid #152333' }}
        >
          <div>
            <h2 className="text-sm font-semibold text-slate-100 tracking-tight">Board Brief</h2>
            <p className="text-[10px] text-slate-600 mt-0.5">
              Auto-generated from current dashboard state · EIA data
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={copyToClipboard}
              className="text-xs text-slate-400 hover:text-teal-300 border border-slate-700/60 hover:border-teal-500/40 rounded-lg px-3 py-1.5 transition-colors"
            >
              Copy
            </button>
            <button
              onClick={download}
              className="text-xs text-teal-400 hover:text-teal-300 border border-teal-500/40 hover:border-teal-500/70 rounded-lg px-3 py-1.5 transition-colors"
              style={{ background: 'rgba(20,184,166,0.05)' }}
            >
              Download
            </button>
            <button
              onClick={onClose}
              className="text-slate-500 hover:text-slate-300 text-lg leading-none ml-1 transition-colors w-7 h-7 flex items-center justify-center"
            >
              ×
            </button>
          </div>
        </div>

        {/* Structured brief content */}
        <div className="flex-1 overflow-y-auto px-6 py-5">
          <BriefRenderer {...rendererProps} />
        </div>

        {/* Footer */}
        <div
          className="px-6 py-3 shrink-0"
          style={{ borderTop: '1px solid #152333' }}
        >
          <p className="text-[9px] text-slate-700 leading-relaxed">
            FieldSignal uses EIA as the trusted data foundation, then adds an AI decision layer for risk detection,
            scenario planning, and executive reporting. Scenario and heuristic outputs are model estimates —
            not official EIA analysis.
          </p>
        </div>
      </div>
    </div>
  );
}
